namespace: m4eba
name: wireguard
version: 0.1.0
readme: README.md
authors:
  - m4eba
description: An ansible collection to install wireguard.
license_file: 'LICENSE'
tags: []
dependencies:
  m4eba.common: '>=0.1.3'
repository: http://github.com/m4eba/ansible-wireguard
issues: http://github.com/m4eba/ansible-wireguard/issues
